config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get 'users/all' => 'users#all', format: :json, as: :users_all
  get 'users/new' => 'users#new'
  get 'users/receivequests' => 'users#receive_quests', format: :json
  get 'users/ranking/:id' => 'users#ranking_user', format: :json
  get 'users/ranking' => 'users#ranking', format: :json
  post 'users/create' => 'users#create', format: :json
  get 'users/:id' => 'users#show', format: :json
  get 'users/:id/edit' => 'users#edit', format: :json, as: :users_edit
  post 'users/:id/follow_deputy' => 'users#follow_deputy', format: :json
  post 'users/:id/unfollow_deputy' => 'users#unfollow_deputy', format: :json
  post 'users/:id/update' => 'users#update', format: :json, as: :users_update
  delete 'users/delete/:id' => 'users#delete', as: :users_delete

  get 'deputies/image/:id' => 'deputies#image'
  get 'deputies/all' => 'deputies#all', format: :json
  get 'deputies/new' => 'deputies#new'
  post 'deputies/create' => 'deputies#create', format: :json
  get 'deputies/:id' => 'deputies#show', format: :json
  post 'deputies/update' => 'deputies#update', format: :json
  get 'deputies/search/:toSearch' => 'deputies#search', format: :json
  get 'users/:id/followed_deputies' => 'deputies#followed_deputies', format: :json
  delete 'deputies/:id' => 'deputies#delete', as: :deputies_delete

  get 'achievements/all' => 'achievements#all', format: :json, as: :achievements_all
  get 'achievements/new' => 'achievements#new', format: :json, as: :achievements_new
  post 'achievements/create' => 'achievements#create', as: :achievements
  get 'achievements/:id' => 'achievements#show', format: :json
  get 'achievements/:id/edit' => 'achievements#edit', format: :json, as: :achievements_edit
  post 'achievements/:id/update' => 'achievements#update',as: :achievements_update
	delete 'achievements/:id' => 'achievements#delete', as: :achievements_delete

  get 'quests/all' => 'quests#all', format: :json, as: :quests_all
  get 'quests/doing' => 'quests#received_quests'
	get 'quests/new' => 'quests#new', format: :json, as: :quests_new
	post 'quests/create' => 'quests#create', as: :quests
	get 'quests/:id' => 'quests#show', format: :json
	post 'quests/:id/update' => 'quests#update', format: :json, as: :quests_update
	get 'quests/:id/edit' => 'quests#edit', format: :json, as: :quests_edit
	delete 'quests/:id' => 'quests#delete', as: :quests_delete

	get 'ufs/all' => 'ufs#all', format: :json
	get 'ufs/new' => 'ufs#new'
 	post 'ufs/create' => 'ufs#create', as: :ufs
	get 'ufs/:id' => 'ufs#show', format: :json
	patch 'ufs/:id/update' => 'ufs#update', format: :json, as: :uf
	delete 'ufs/:id' => 'ufs#delete', as: :ufs_delete

	get 'parties/all' => 'parties#all', format: :json
	get 'parties/new' => 'parties#new'
	post 'parties/create' => 'parties#create', as: :parties
	get 'parties/:id' => 'parties#show', format: :json
	patch 'parties/:id/update' => 'parties#update', format: :json, as: :party
	get 'parties/:id/edit' => 'parties#edit'
	delete 'parties/:id' => 'parties#delete', as: :parties_delete

  get 'levels/all' => 'levels#all', format: :json

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/signin' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  #ionic login
  get 'signIn' => 'users#ionic_login'
end

app/models/quest.rb
class Quest < ActiveRecord::Base
	acts_as :gamification

	has_many :user_relationships, class_name: "QuestRelationship",
																foreign_key: "challenger_id",
																dependent: :destroy

	has_many :challengeds, through: :user_relationships, source: :challenged

	belongs_to :user
# :nocov:
	def self.parse_quests
		quests = [["Seguir 10 deputados", 100, "Siga 10 deputados"],
		["Entre 5 vezes", 150, "Você deve entrar no app 5 vezes"],
		["Siga Baleia Rossi", 500, "Você deve seguir o deputado Baleia Rossi"],
		["Siga família Bolsonaro", 250, "Você deve seguir Bolso"],
		["Siga Jean Wyllys", 150, "Você deve seguir Jean Wyllys"],
		["Entre 10 vezes", 300, "Você deve entrar no app 10 vezes"],
		["Suba de level", 100, "Você deve evoluir um level"],
		["Suba 10 leveis", 500, "Você deve evoluir 10 leveis"],
		["Complete 10 achievements", 1000, "Você deve completar 10 achievements"],
		["Siga um deputado do PT", 100, "Você deve seguir um deputado do PT"]]

		if Quest.all.length >= 10
			puts "Base de quests já populada!"
		else
			quests.each do |quest|
				new_quest = Quest.new(:name => quest[0], :experience_points => quest[1],
				:description => quest[2])
				if new_quest.save
					puts "Quest :" + quest[0] + " Adicionada"
				end
			end
		end
	end
# :nocov:
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

	def all
		@quest = Quest.all

		respond_to do |format|
			format.html
			format.json {render json: @quest}
		end
	end

	def show
		quest_id = params[:id]
		selected_quests = Quest.where(id: quest_id)
		@quest = nil
		if selected_quests.length > 0
			@quest = selected_quests.first
		else
			raise "ERROR"
		end
		render json: @quest
	end

	def new
		@quest = Quest.new
	end

	def create
		@quest = Quest.new(quest_params)
		if @quest.save
			redirect_to :quests_all
		else
			render 'new'
		end
	end

	def edit

		@quest = Quest.find(params[:id])
		render 'edit'

	end

	def update
		@quest = Quest.find(params[:id])

		if @quest.update(quest_params)
			redirect_to :quests_all
		else
			render 'edit'
		end
	end

	def delete
		id_quest = params[:id]
		quests = Quest.where(id: id_quest)
		quest = quests.first
		quest.destroy
		redirect_to :quests_all
	end

#:nocov:
	def received_quests
		user_id = params[:userId]
		user = User.find_by(id: user_id)
		received_quests = user.challengers
		if user.challengers
			render json: received_quests
		else
			raise "ERROR"
		end
	end
#:nocov:

	private

	def quest_params
		params.require(:quest).permit(:name, :experience_points, :description)
	end
end

app/views/quests/all.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
	<%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
			<h1 id="tittle" class="brand-logo">PurrSuit</h1>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li><%= link_to "Achievements", :achievements_all %></li>
          <li><%= link_to "Users", :users_all %></li>
        	<li class="active"><%= link_to "Quests", :quests_all%></li>
			<li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
    <div class="principalSquare">
		<% if current_user && current_user.admin? %>
	      <div class="listSquare">
				<% @quest.each do | q | %>
	          <div class="panel panel-default">
	            <div class="panel-heading">
	              <h3 class="panel-title"><%= q.name %></h4>
	                <span class="label label-default"><%= q.experience_points %> Experience Points</span>
	            </div>
	            <div class="panel-body">
	              <%= q.description%>
	              <div class="btn-toolbar button_group" role="group">
	                <%= button_to "Edit", quests_edit_path(q), :method => :get, :id => "option-button", :class => "btn btn-default btn-xs" %>
	                <%= button_to "Delete", quests_delete_path(q), :method => :delete, :id => "option-button", :class => "option_button btn btn-default btn-xs", data: { confirm: 'Você tem certeza que quer deletar esta quest?' } %>
	              </div>
	              </div>
	            </div>
	          <% end %>
	      </div>
			<% else %>
			  <script type="text/javascript">
			    window.location.href="/logout"
			  </script>
			<% end %>
    </div>
		<a href="new" id="newThing" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
  </body>
</html>

app/views/quests/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
	<%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
			<h1 id="tittle" class="brand-logo">PurrSuit</h1>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li><%= link_to "Achievements", :achievements_all %></li>
          <li><%= link_to "Users", :users_all %></li>
        	<li class="active"><%= link_to "Quests", :quests_all%></li>
			<li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
    <div class="principalSquare">
    <% if current_user && current_user.admin? %>
      <div class="listSquare">
        <%= form_for :quest, url: quests_update_path, method: :put do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Quest's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Save", :id => "gamification_button", :class => "btn btn-default btn-xs"%>
        <% end %>
        <%= button_to "Cancel", :quests_all, :id => "gamification_button", :class => "btn btn-default btn-xs", :method => :get %>
      </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    </div>
  </body>
</html>

app/views/quests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
	<%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
			<h1 id="tittle" class="brand-logo">PurrSuit</h1>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li><%= link_to "Achievements", :achievements_all %></li>
          <li><%= link_to "Users", :users_all %></li>
        	<li class="active"><%= link_to "Quests", :quests_all%></li>
			<li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
    <div class="principalSquare">
    <% if current_user && current_user.admin? %>
      <div class="listSquare">
        <%= form_for(@quest) do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Quest's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Create", :id => "gamification_button", :class => "btn btn-default btn-xs"%>
        <% end %>
        <%= button_to "Cancel", :quests_all, :id => "gamification_button", :class => "btn btn-default btn-xs", :method => :get %>
      </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    </div>
  </body>
</html>

app/views/quests/show.html.erb
      <% if current_user && current_user.admin? %> 
			<% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>


<p>
  <strong>Name:</strong>
  <%= @quest.name %>
</p>
  <strong>Description:</strong>
  <%= @quest.description %>
</p>

<p>
<strong>Experience:</strong>
<%= @quest.experience_points %>
</p>

<%= button_to 'Delete', quests_delete_path , method: :delete %>
<%= button_to 'Delete', quests_delete_path , method: :delete %>