config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get 'users/all' => 'users#all', format: :json, as: :users_all
  get 'users/new' => 'users#new'
  get 'users/receivequests' => 'users#receive_quests', format: :json
  get 'users/ranking/:id' => 'users#ranking_user', format: :json
  get 'users/ranking' => 'users#ranking', format: :json
  post 'users/create' => 'users#create', format: :json
  get 'users/:id' => 'users#show', format: :json
  get 'users/:id/edit' => 'users#edit', format: :json, as: :users_edit
  post 'users/:id/follow_deputy' => 'users#follow_deputy', format: :json
  post 'users/:id/unfollow_deputy' => 'users#unfollow_deputy', format: :json
  post 'users/:id/update' => 'users#update', format: :json, as: :users_update
  delete 'users/delete/:id' => 'users#delete', as: :users_delete

  get 'deputies/image/:id' => 'deputies#image'
  get 'deputies/all' => 'deputies#all', format: :json
  get 'deputies/new' => 'deputies#new'
  post 'deputies/create' => 'deputies#create', format: :json
  get 'deputies/:id' => 'deputies#show', format: :json
  post 'deputies/update' => 'deputies#update', format: :json
  get 'deputies/search/:toSearch' => 'deputies#search', format: :json
  get 'users/:id/followed_deputies' => 'deputies#followed_deputies', format: :json
  delete 'deputies/:id' => 'deputies#delete', as: :deputies_delete

  get 'achievements/all' => 'achievements#all', format: :json, as: :achievements_all
  get 'achievements/new' => 'achievements#new', format: :json, as: :achievements_new
  post 'achievements/create' => 'achievements#create', as: :achievements
  get 'achievements/:id' => 'achievements#show', format: :json
  get 'achievements/:id/edit' => 'achievements#edit', format: :json, as: :achievements_edit
  post 'achievements/:id/update' => 'achievements#update',as: :achievements_update
	delete 'achievements/:id' => 'achievements#delete', as: :achievements_delete

  get 'quests/all' => 'quests#all', format: :json, as: :quests_all
  get 'quests/doing' => 'quests#received_quests'
	get 'quests/new' => 'quests#new', format: :json, as: :quests_new
	post 'quests/create' => 'quests#create', as: :quests
	get 'quests/:id' => 'quests#show', format: :json
	post 'quests/:id/update' => 'quests#update', format: :json, as: :quests_update
	get 'quests/:id/edit' => 'quests#edit', format: :json, as: :quests_edit
	delete 'quests/:id' => 'quests#delete', as: :quests_delete

	get 'ufs/all' => 'ufs#all', format: :json
	get 'ufs/new' => 'ufs#new'
 	post 'ufs/create' => 'ufs#create', as: :ufs
	get 'ufs/:id' => 'ufs#show', format: :json
	patch 'ufs/:id/update' => 'ufs#update', format: :json, as: :uf
	delete 'ufs/:id' => 'ufs#delete', as: :ufs_delete

	get 'parties/all' => 'parties#all', format: :json
	get 'parties/new' => 'parties#new'
	post 'parties/create' => 'parties#create', as: :parties
	get 'parties/:id' => 'parties#show', format: :json
	patch 'parties/:id/update' => 'parties#update', format: :json, as: :party
	get 'parties/:id/edit' => 'parties#edit'
	delete 'parties/:id' => 'parties#delete', as: :parties_delete

  get 'levels/all' => 'levels#all', format: :json

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/signin' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  #ionic login
  get 'signIn' => 'users#ionic_login'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as :person
  belongs_to :level
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :quests_relationships, class_name: "QuestRelationship",
                                foreign_key: "challenged_id",
                                dependent: :destroy
  has_many :challengers, through: :quests_relationships, source: :challenger

  has_many :quests

  has_secure_password

  validates :email, presence: true, length: {maximum: 255}
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	validates :nickname, presence: true, length: { maximum: 20 }, uniqueness: true
# :nocov:
  def admin?
    self.role_admin
  end
# :nocov:
  def follow(deputy)
    active_relationships.create(followed_id: deputy.id)
    deputy.followers_count += 1
    deputy.save
  end

  def unfollow(deputy)
    active_relationships.find_by(followed_id: deputy.id).destroy
    deputy.followers_count -= 1
    deputy.save
  end

  def following?(deputy)
    following.include?(deputy)
  end

  def receive_quest(quest)
    quests_relationships.create(challenger_id: quest.id)
  end

  def complete_quest(quest)
    quests_relationships.find_by(challenger_id: quest.id).destroy
  end

  def doing?(quest)
    relationships = QuestRelationship.where(challenged_id: self.id)
    doing_quests = []
    relationships.each do |quest|
      doing_quests << Quest.find(quest.challenger_id)
    end
    doing_quests.include?(quest)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter  :verify_authenticity_token

  def all
		respond_to do |format|
			format.html {@user = User.where(["nickname LIKE ?", "%#{params[:search]}%"])}
			format.json {render json: User.all}
		end
  end

  def ranking
    ranking = users_by_XP
    result = []
    ranking[0..19].each do |user|
      result << user
    end
    render json: result
  end

  def ranking_user
    id_user = params[:id]
    user = User.find(id_user)
    ranking = users_by_XP
    position = []

    position << ranking.index(user) + 1
    render json: position
  end

  def show
    id_user = params[:id]
    users = User.where(id: id_user)
    @user = nil
    if (users.length > 0)
      @user = users.first
    else
      raise "ERROR: No user to be shown"
    end
    render json: @user
  end

  def new
    @user = User.new
    render :nothing =>true
  end

  def create
    #puts get_params
    @user = User.new(user_params)
    saved = @user.save
    begin
      if saved
        session[:user_id] = @user.id
        render json: @user
      else
        render :nothing=>true
        raise "sign up failed"
      end
    rescue RuntimeError => error_signup
      puts "#{error_signup}"
    end

    #render json: User.new
  end

  def edit
    id_users = params[:id]
    user = nil
    users = User.where(id: id_users)
    @user = users.first
    render :edit
  end

  def update
    user_id = params[:id]
    @user = User.find_by(id: user_id)
    @user.update(user_update_params)
    respond_to do |format|
      format.json {render json: @user}
      format.html {redirect_to :users_all}
    end
  end

  def delete
    user_id = params[:id]
    user = User.find_by(id: user_id)
    puts "#{user}"
      if user
        user.delete
				redirect_to :users_all
      end
  end

  def follow_deputy
    deputy_id = params[:deputyId]
    user_id = params[:userId]
    user = User.find_by(id: user_id)
    deputy = Deputy.find_by(id: deputy_id)
    user.follow(deputy)
    render :nothing => true
  end

  def unfollow_deputy
    deputy_id = params[:deputyId]
    user_id = params[:userId]
    user = User.find_by(id: user_id)
    deputy = Deputy.find_by(id: deputy_id)
    user.unfollow(deputy)
    render :nothing => true
  end

  def ionic_login
    @user = User.find_by(email: params[:email])
    begin
      if @user && @user.authenticate(params[:password])
        render json: @user
      else
        raise "login failed!"
      end
    rescue RuntimeError => error_login
      puts "#{error_login}"
      redirect_to 'login'
    end
  end

  def receive_quests
    user_id = params[:userId]
    user = User.find_by(id: user_id)
    questsAmount = params[:questsAmount]

    if user && user.challengers.length < 3
      allQuests = []
      Quest.all.each do |quest|
        allQuests << quest if !user.doing?(quest) && !user.quests.include?(quest)
      end

      questsAmount.to_i.times do
        random = allQuests.sample
        user.receive_quest(random)
        allQuests.delete(random)
      end

    end
    render :nothing => true
  end

  private
    def user_params
      params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
    end

    def user_update_params
      params.require(:user).permit(:name, :nickname, :experience_points, :email,
      :password, :gender, :age, :level, :uf_id, :last_acess)
    end

    def users_by_XP
      users = User.all
      ranking = users.sort_by do |user|
        [-user.experience_points, user.nickname]
      end
    end
end

app/views/users/all.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  <%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
      <h1 id="tittle" class="brand-logo">PurrSuit</h1>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Achievements", :achievements_all %></li>
					<li class="active"><%= link_to "Users", :users_all %></li>
          <li><%= link_to "Quests", :quests_all%></li>
      <li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
    <div class="principalSquare">
    <% if current_user && current_user.admin? %>
        <div class="listSquare">
				<%= form_tag users_all_path, :method => 'get' do %>
					<%= text_field_tag :search, params[:search], :id => "searchTF" %>
					<button id="search-button"class="btn btn-default btn-xs" type="submit" name="action">
						Search
  				</button>
				<br><br>
				<% if @user.size == 0 %>
					<div id="alert" class="alert alert-danger" role="alert">Usuário <%= params[:search] %> não encontrado</div>
				<% end %>
				<% end %>
        <% @user.each do | q | %>
            <% if !q.role_admin %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= q.nickname %></h4>
                  <span class="label label-default"><%= q.experience_points %> Experience Points</span>
              </div>
              <div class="panel-body">
                <%= q.email%>
                <div class="btn-toolbar button_group" role="group">
                  <%= button_to "Edit", users_edit_path(q), :method => :get, :class => "btn btn-default btn-xs" %>
                  <%= button_to "Delete", users_delete_path(q), :method => :delete, :class => "btn btn-default btn-xs", data: { confirm: 'Você tem certeza que quer deletar este usuário?' } %>
                </div>
                </div>
              </div>
              <% end %>
            <% end %>
        </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  <%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
      <h1 id="tittle" class="brand-logo">PurrSuit</h1>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Achievements", :achievements_all %></li>
          <li class="active"><%= link_to "Users", :users_all %></li>
          <li><%= link_to "Quests", :quests_all%></li>
      <li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
    <div class="principalSquare">
    <% if current_user && current_user.admin? %>
      <div class="listSquare">
        <%= form_for :user, url: users_update_path, method: :post do | form | %>
          <%= form.text_field :nickname, :class => "gamification_fields", :placeholder => "User's nickname"%>
          <%= form.text_field :email, :class => "gamification_fields", :placeholder => "Email" %>
          <%= form.submit "Save", :id => "gamification_button", :class => "btn btn-default btn-xs"%>
        <% end %>
        <%= button_to "Cancel", :users_all, :id => "gamification_button", :class => "btn btn-default btn-xs", :method => :get %>
      </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%= form_for :user, url: :users_create, html: {method: "POST"} do |f| %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %><br>
      <%= f.label :age, "Idade" %>
      <%= f.number_field :age, min: 0, max: 200 %><br>
      <%= f.label :gender, "Sexo" %>
      <%= f.radio_button :gender, "Masculino" , checked: true %>Masculino
      <%= f.radio_button :gender, "Feminino" %>Feminino<br>
      <%= f.label :email, "E-mail" %>
      <%= f.email_field :email %><br>
      <%= f.label :password, "Senha" %>
      <%= f.password_field :password %><br>
      <%= f.label :password_confirmation, "Confirme a senha" %>
      <%= f.password_field :password_confirmation %><br>
      <%= f.submit "create account" %>
    <% end %>
  </body>
</html>