config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get 'users/all' => 'users#all', format: :json, as: :users_all
  get 'users/new' => 'users#new'
  get 'users/receivequests' => 'users#receive_quests', format: :json
  get 'users/ranking/:id' => 'users#ranking_user', format: :json
  get 'users/ranking' => 'users#ranking', format: :json
  post 'users/create' => 'users#create', format: :json
  get 'users/:id' => 'users#show', format: :json
  get 'users/:id/edit' => 'users#edit', format: :json, as: :users_edit
  post 'users/:id/follow_deputy' => 'users#follow_deputy', format: :json
  post 'users/:id/unfollow_deputy' => 'users#unfollow_deputy', format: :json
  post 'users/:id/update' => 'users#update', format: :json, as: :users_update
  delete 'users/delete/:id' => 'users#delete', as: :users_delete

  get 'deputies/image/:id' => 'deputies#image'
  get 'deputies/all' => 'deputies#all', format: :json
  get 'deputies/new' => 'deputies#new'
  post 'deputies/create' => 'deputies#create', format: :json
  get 'deputies/:id' => 'deputies#show', format: :json
  post 'deputies/update' => 'deputies#update', format: :json
  get 'deputies/search/:toSearch' => 'deputies#search', format: :json
  get 'users/:id/followed_deputies' => 'deputies#followed_deputies', format: :json
  delete 'deputies/:id' => 'deputies#delete', as: :deputies_delete

  get 'achievements/all' => 'achievements#all', format: :json, as: :achievements_all
  get 'achievements/new' => 'achievements#new', format: :json, as: :achievements_new
  post 'achievements/create' => 'achievements#create', as: :achievements
  get 'achievements/:id' => 'achievements#show', format: :json
  get 'achievements/:id/edit' => 'achievements#edit', format: :json, as: :achievements_edit
  post 'achievements/:id/update' => 'achievements#update',as: :achievements_update
	delete 'achievements/:id' => 'achievements#delete', as: :achievements_delete

  get 'quests/all' => 'quests#all', format: :json, as: :quests_all
  get 'quests/doing' => 'quests#received_quests'
	get 'quests/new' => 'quests#new', format: :json, as: :quests_new
	post 'quests/create' => 'quests#create', as: :quests
	get 'quests/:id' => 'quests#show', format: :json
	post 'quests/:id/update' => 'quests#update', format: :json, as: :quests_update
	get 'quests/:id/edit' => 'quests#edit', format: :json, as: :quests_edit
	delete 'quests/:id' => 'quests#delete', as: :quests_delete

	get 'ufs/all' => 'ufs#all', format: :json
	get 'ufs/new' => 'ufs#new'
 	post 'ufs/create' => 'ufs#create', as: :ufs
	get 'ufs/:id' => 'ufs#show', format: :json
	patch 'ufs/:id/update' => 'ufs#update', format: :json, as: :uf
	delete 'ufs/:id' => 'ufs#delete', as: :ufs_delete

	get 'parties/all' => 'parties#all', format: :json
	get 'parties/new' => 'parties#new'
	post 'parties/create' => 'parties#create', as: :parties
	get 'parties/:id' => 'parties#show', format: :json
	patch 'parties/:id/update' => 'parties#update', format: :json, as: :party
	get 'parties/:id/edit' => 'parties#edit'
	delete 'parties/:id' => 'parties#delete', as: :parties_delete

  get 'levels/all' => 'levels#all', format: :json

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/signin' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  #ionic login
  get 'signIn' => 'users#ionic_login'
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	acts_as :gamification

end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

	def all
		@achievement = Achievement.all

		respond_to do |format|
			format.html
			format.json {render json: @achievement}
		end
	end

	def show
		achievement_id = params[:id]
		selected_achievements = Achievement.where(id: achievement_id)
		@achievement = nil
		if selected_achievements.length > 0
			@achievement = selected_achievements.first
		else
			raise "ERROR"
		end
		render json: @achievement
	end

	def new
		@achievement = Achievement.new
	end

	def create
		@achievement = Achievement.new(achievement_params)
		if @achievement.save
			redirect_to :achievements_all
		end
	end

	def edit
		@achievement = Achievement.find(params[:id])
		render 'edit'
	end

	def update
		@achievement = Achievement.find(params[:id])
		if @achievement.update(achievement_params)
			redirect_to :achievements_all
		else
			render 'edit'
		end
	end

	def delete
		id_achievement = params[:id]
		achievements = Achievement.where(id: id_achievement)
		achievement = achievements.first
		achievement.destroy
		redirect_to :achievements_all

	end

	private

	def achievement_params
		params.require(:achievement).permit(:name, :experience_points, :description)
	end
end

app/views/achievements/all.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
	<%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
			<h1 id="tittle" class="brand-logo">PurrSuit</h1>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li class="active"><%= link_to "Achievements", :achievements_all %></li>
          <li><%= link_to "Users", :users_all %></li>
        	<li><%= link_to "Quests", :quests_all%></li>
					<li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
		<div class="principalSquare">
    <% if current_user && current_user.admin? %>
			<div class="listSquare">
				<% @achievement.each do | a | %>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title"><%= a.name %></h3>
							<span class="label label-default"><%= a.experience_points %> Experience Points</span>
						</div>
						<div class="panel-body">
							<%= a.description%><br>
							<div class="btn-toolbar button_group" role="group">
								<%= button_to "Edit", achievements_edit_path(a), :method => :get, :id => "option-button", :class => "btn btn-default btn-xs" %>
								<%= button_to "Delete", achievements_delete_path(a), :method => :delete, :id => "option-button", :class => "btn btn-default btn-xs", data: { confirm: 'Você tem certeza que quer deletar esta achievement?' } %>
							</div>
						</div>
					</div>
        		<% end %>
     		 </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
		</div>
		<a href="new" id="newThing" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
	</body>
</html>

app/views/achievements/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
	<%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
			<h1 id="tittle" class="brand-logo">PurrSuit</h1>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li class="active"><%= link_to "Achievements", :achievements_all %></li>
          <li><%= link_to "Users", :users_all %></li>
        	<li><%= link_to "Quests", :quests_all%></li>
					<li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
    <div class="principalSquare">
    <% if current_user && current_user.admin? %>
      <div class="listSquare">
        <%= form_for :achievement, url: achievements_update_path, method: :put do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Achievement's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Save", :id => "gamification_button", :class => "btn btn-default btn-xs"%>
        <% end %>
        <%= button_to "Cancel", :achievements_all, :id => "gamification_button", :class => "btn btn-default btn-xs", :method => :get %>
      </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    </div>
  </body>
</html>

app/views/achievements/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
	<%= stylesheet_link_tag "materialize.css" %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="boddy">
    <nav>
      <div class="nav-wrapper">
        <img src="<%= asset_path('PurrsuitPersonagem.png')%>" class="purrSuitImage other-page" />
			<h1 id="tittle" class="brand-logo">PurrSuit</h1>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li class="active"><%= link_to "Achievements", :achievements_all %></li>
          <li><%= link_to "Users", :users_all %></li>
        	<li><%= link_to "Quests", :quests_all%></li>
					<li><%= link_to "Logout", logout_path%></li>
      </ul>
    </nav>
   <div class="principalSquare">
    <% if current_user && current_user.admin? %>
      <div class="listSquare">
				<%= form_for(@achievement) do | form | %>
     		  <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Achievement's name"%>
   			  <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
    		  <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
  		    <%= form.submit "Create", :id => "gamification_button", :class => "btn btn-default btn-xs"%>
		    <% end %>
        <%= button_to "Cancel", :achievements_all, :class => "btn btn-default btn-xs", :id => "gamification_button", :method => :get %>
      </div>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    </div>
  </body>
</html>

app/views/achievements/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
      <% if current_user && current_user.admin? %>
      <% else %>
        <script type="text/javascript">
          window.location.href="/logout"
        </script>
      <% end %>
    <h1><%= @achievement.name %></h1>
    <h3><%= @achievement.experience_points %></h3>
    <h5><%= @achievement.description %></h3>
  </body>
</html>